spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/devblog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwe123
    hikari:
      connection-init-sql: SET NAMES utf8mb4

  exposed:
    show-sql: true
    generate-ddl: true

# 로깅 설정
logging:
  level:
    blog.vans_story_be: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 서버 설정
server:
  port: 8080