spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devblog?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: qwe123

  jpa:
    hibernate:
      ddl-auto: create  # 개발 환경이므로 create 유지
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# 로깅 설정 (기존과 동일)
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    com.blog: debug
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 서버 설정 (기존과 동일)
server:
  port: 8080