spring:
  # 데이터베이스 연결 설정
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 운영 데이터베이스 연결 정보
    url: jdbc:mariadb://your-production-db:3306/blog_prod?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # 환경 변수에서 데이터베이스 접속 정보를 가져옴 (보안)
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# Exposed 설정
exposed:
  generate-ddl: false  # 운영 환경에서는 DDL 생성 비활성화
  show-sql: false      # SQL 로그 출력 비활성화

# 로깅 설정 (운영 환경에서는 최소한의 로깅만 수행)
logging:
  level:
    org.jetbrains.exposed: info
    com.blog: info

# 서버 설정
server:
  port: 80    # 운영 서버 포트